name: Deploy App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project
        run: mvn clean install -DskipTest

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t augustod3v/deploy_aws_java .

      - name: Push image docker
        run: docker push augustod3v/deploy_aws_java

  build-on-aws:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker
        run: sudo docker pull augustod3v/deploy_aws_java

      - name: Remove docker container
        run: sudo docker rm -f deploy_aws_java

      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name deploy_aws_java augustod3v/deploy_aws_java
